### ISSUE TITLE
bug install on ubuntu 16, SSH problem

### ISSUE THREAD

**Issue by resethread** [uonick/vagrant-php7-phalcon#1]
Hi, 
I have a problem to run the vagrant box.
This is the last line in the script :
default: SSH auth method: private key

What should I do to run the box ?
Thanks.

**Comment by uonick** [comment]
Hi! Look here for solutions:

* https://laracasts.com/discuss/channels/general-discussion/virtualbox-vagrant-homestead-ssh-issue

* http://computingforgeeks.com/how-to-fix-vagrant-ssh-authentication-failure-after-packaging-vagrant-box/

* http://stackoverflow.com/questions/22922891/vagrant-ssh-authentication-failure

And make sure that you use the latest version. This bug in ubuntu 16.10 from previous commits. In latest version is fixed.

**Comment by uonick** [comment]
@resethread, the problem is solved?

**Comment by resethread** [comment]
Hey, yes thanks 👍
