### ISSUE TITLE
Cannot open directory.dev website

### ISSUE THREAD

**Issue by eugenezabolotny** [uonick/vagrant-php7-phalcon#2]
Cannot open directory.dev website. When I try add into /etc/hosts IP related to domain I get 404 error. I made everything step by step by readme file.

**Comment by uonick** [comment]
@eugenezabolotny hi!

Хотелось бы глянуть на:
1. `ping directory.dev`
2. `/etc/hosts`
3. `ping 192.168.3.3`
4. Версию Linux/macOS

**Comment by eugenezabolotny** [comment]
Смена имени папки с `./public_html/` на `./public` решило проблему. Добавить бы этот пункт явно в мануал.
Спасибо за оперативный ответ.

**Comment by uonick** [comment]
Никто не говорил, что оно должно быть `./public_html/` 😉 . 

Пункт в документацию будет добавлен 👍
